### ISSUE TITLE
Question about adapting your work

### ISSUE THREAD

**Issue by SofienBoutaib** [MelihAltintas/AutomaticJavaCodeSmellDetector#1]
I like your work and I tried to adopt it as a project, not a plugin but I didn't know how !! can you help me?! the location of the class main and where can I put the path of the project to be parsed!!

**Comment by MelihAltintas** [comment]
Normally, Eclipse JDT is used in a plug-in environment. This is the normal situation in which we deal with each project in the workspace. However, if we want to parse java files in standalone application you could like that: https://www.programcreek.com/2011/01/a-complete-standalone-example-of-astparser/

**Comment by SofienBoutaib** [comment]
Okay. I will try what send it to do what you said to me. For the detection of metrics, can I perform what you do or not?
